apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
data:
  PORT: NDUwMA==
  MYSQL_HOST: dHdvLXRpZXIuYzE0NmNjY3U0b2hrLmFwLXNvdXRoLTEucmRzLmFtYXpvbmF3cy5jb20g
  MYSQL_USER: YWRtaW4=
  MYSQL_PASS: Qkx0ekVDQnVnRDg3UXNn
  MYSQL_DB: dHdvLXRpZXI=
